Writable:
  LogLevel: "DEBUG"

Service:
  Host: localhost
  Port: 59982
  StartupMsg: device mqtt started

MqttBrokerInfo:
  Schema: "tcp"
  Host: "edgex-mqtt-broker"
  Port: 1883
  Qos: 1
  KeepAlive: 3600
  RetainedAutoevent: false
  ResponseTopic: "commandresponses/#"
  IncomingTopic: "incoming/data/#"
  
Device:
  ProfilesDir: "/custom-config/profiles"
  DevicesDir: "/custom-config/devices"
  UpdateLastConnected: false
  AsyncBufferSize: 1
  EnableAsyncReadings: true
  MaxConcurrentRequests: 30
